# AI Models
LLM_MODEL = "gemini-2.5-flash" # model that powers the agent
EMBEDDING_MODEL = "gemini-embedding-001" # embedding model that generates embeddings (gemini-embedding-2-preview)

# number of vector dimensions generated by the embedding model
EMBEDDING_DIMENSIONS = 1536

# SQL max rows to fetch
MAX_LIMIT = 10
